name: run-tests
on:
  push:
    branches: [ main, develop, feature/*, release/*, hotfix/* ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 0 * * *'
jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [7.4, 8.0, 8.1, 8.2, 8.3]
        laravel: [8.*, 9.*, 10.*, 11.*]
        dependency-version: [prefer-lowest, prefer-stable]
        experimental: [false]
        include:
          - php: 8.4
            experimental: true
            os: ubuntu-latest
            dependency-version: prefer-lowest
            laravel: 8.*
          - php: 8.4
            experimental: true
            os: ubuntu-latest
            dependency-version: prefer-stable
            laravel: 9.*
          - php: 8.4
            experimental: true
            os: ubuntu-latest
            dependency-version: prefer-stable
            laravel: 10.*
          - php: 8.4
            experimental: true
            os: ubuntu-latest
            dependency-version: prefer-stable
            laravel: 11.*
          - laravel: 11.*
            testbench: ^9.2.0
            pest-laravel: ^2.4.0
            pest: ^2.34.9
          - laravel: 10.*
            testbench: ^8.15.0
            pest-laravel: ^1.4.0
            pest: ^1.23.1
          - laravel: 9.*
            testbench: ^7.35.0
            pest-laravel: ^1.4.0
            pest: ^1.23.1
          - laravel: 8.*
            testbench: ^6.38.0
            pest-laravel: ^1.4.0
            pest: ^1.23.1
        exclude:
          - laravel: 11.*
            php: 7.4
          - laravel: 11.*
            php: 8.0
          - laravel: 11.*
            php: 8.1
          - laravel: 10.*
            php: 7.4
          - laravel: 10.*
            php: 8.0
          - laravel: 9.*
            php: 7.4

    name: PHP-${{ matrix.php }} - OS-${{ matrix.os }} L-${{ matrix.laravel }} - ${{ matrix.dependency-version }} - Experimental- ${{ matrix.experimental }}

    steps:
      - name: Update apt
        run: sudo apt-get update --fix-missing

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, json, mbstring
          coverage: xdebug

      - name: Install dependencies
        run: |
          composer self-update
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer require --dev "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer require --dev "pestphp/pest-plugin-laravel:${{ matrix.pest-laravel }}" --no-interaction --no-update
          composer require --dev "pestphp/pest:${{ matrix.pest }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction
          composer dump-autoload
          composer validate --no-check-all --strict

      - name: Execute tests
        run: composer run-script test

      - name: Upload coverage
        if: ${{ github.event_name != 'schedule' && matrix.php == '8.3' && matrix.dependency-version == 'prefer-stable' && matrix.laravel == '11.*' }}
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
      - name: Upload code climate
        if: ${{ github.event_name != 'schedule' && matrix.php == '8.3' && matrix.dependency-version == 'prefer-stable' && matrix.laravel == '11.*' }}
        uses: paambaati/codeclimate-action@v8
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: ${{ github.workspace }}/coverage.xml:clover
